import { ComponentFixture, TestBed } from '@angular/core/testing';
import { HttpTestingController } from '@angular/common/http/testing';
import { AgentePacienteComponent } from './agente-paciente.component';
import { BASE, PROVEEDORES_PRUEBA, iniciarSesionCon } from '../nucleo/pruebas/sesion-sintetica';

const RUTA=`${BASE}/asistente/pacientes/pac-1/sesiones`;
const respuesta=(extra:Record<string,unknown>={})=>({sesion_id:'hilo-1',paciente_id:'pac-1',expira_en:'2099-01-01T00:00:00Z',texto:'Ficha vinculada',datos:{},propuesta:null,requiere_humano:false,modo:'local',...extra});
const propuesta={id:'prop-1',nombre:'cancel_appointment',titulo:'Cancelar cita',argumentos:{cita_id:'identificador-privado',motivo:'Solicitud de cambio'},expira_en:'2099-01-01T00:00:00Z'};

describe('AgentePacienteComponent',()=>{
  let f:ComponentFixture<AgentePacienteComponent>;let http:HttpTestingController;
  beforeEach(()=>{TestBed.configureTestingModule({imports:[AgentePacienteComponent],providers:PROVEEDORES_PRUEBA});iniciarSesionCon(['paciente.leer_administrativo','agenda.leer','cita.crear','cita.cancelar','cita.reprogramar','pago.leer','historia_clinica.leer']);f=TestBed.createComponent(AgentePacienteComponent);f.componentRef.setInput('pacienteId','pac-1');f.componentRef.setInput('nombre','Paciente Sintético');http=TestBed.inject(HttpTestingController);});
  afterEach(()=>http.verify());
  function iniciar(){f.detectChanges();const r=http.expectOne(RUTA);expect(r.request.method).toBe('POST');expect(r.request.headers.has('Idempotency-Key')).toBe(true);r.flush(respuesta());f.detectChanges();}
  function boton(texto:string){const b=Array.from(f.nativeElement.querySelectorAll('button')) as HTMLButtonElement[];const encontrado=b.find(x=>x.textContent?.trim()===texto);expect(encontrado).toBeDefined();encontrado!.click();f.detectChanges();return encontrado!;}
  function decir(texto='Mis citas',r=respuesta()){boton(texto);http.expectOne(`${RUTA}/hilo-1/mensajes`).flush(r);f.detectChanges();}
  it('abre solo el paciente recibido y declara modo local',()=>{iniciar();expect(f.nativeElement.textContent).toContain('Paciente Sintético');expect(f.nativeElement.textContent).toContain('IA externa pendiente');expect(f.nativeElement.querySelector('[name="paciente"]')).toBeNull();});
  it('mantiene la conversación al refrescar la cita de la ficha',()=>{iniciar();f.componentRef.setInput('citaId','cita-actualizada');f.detectChanges();http.expectNone(RUTA);expect(f.nativeElement.textContent).toContain('Ficha vinculada');});
  it('abre otra sesión al cambiar de paciente y usa su nueva ruta',()=>{iniciar();f.componentRef.setInput('pacienteId','pac-2');f.detectChanges();http.expectOne(`${BASE}/asistente/pacientes/pac-2/sesiones`).flush(respuesta({paciente_id:'pac-2'}));f.detectChanges();boton('Mis citas');http.expectOne(`${BASE}/asistente/pacientes/pac-2/sesiones/hilo-1/mensajes`).flush(respuesta());});
  it('muestra citas y permite seleccionarlas sin pedir historias ajenas',()=>{iniciar();decir('Mis citas',respuesta({datos:{citas:[{cita_id:'cita-1',inicio:'2026-04-16T15:00:00Z',estado:'CONFIRMED'}]}}));expect(f.nativeElement.textContent).toContain('Confirmada');boton('Usar esta cita');const r=http.expectOne(`${RUTA}/hilo-1/cita`);expect(r.request.body).toEqual({cita_id:'cita-1'});r.flush(respuesta());});
  it('la propuesta exige confirmación y oculta identificadores técnicos',()=>{iniciar();decir('Mis citas',respuesta({propuesta}));expect(f.nativeElement.textContent).toContain('Solicitud de cambio');expect(f.nativeElement.textContent).not.toContain('identificador-privado');http.expectNone(`${RUTA}/hilo-1/confirmar`);const accion=(Array.from(f.nativeElement.querySelectorAll('button')) as HTMLButtonElement[]).find(b=>b.textContent?.trim()==='Mis citas') as HTMLButtonElement;expect(accion.disabled).toBe(true);});
  it('confirma una propuesta y avisa a la ficha para refrescar la agenda',()=>{iniciar();decir('Mis citas',respuesta({propuesta}));const aviso=vi.fn();f.componentInstance.actualizado.subscribe(aviso);boton('Confirmar acción');const r=http.expectOne(`${RUTA}/hilo-1/confirmar`);expect(r.request.body).toEqual({propuesta_id:'prop-1',aceptar:true});r.flush(respuesta({texto:'Cita cancelada'}));expect(aviso).toHaveBeenCalledOnce();});
  it('descarta sin pedir refresco por una escritura',()=>{iniciar();decir('Mis citas',respuesta({propuesta}));const aviso=vi.fn();f.componentInstance.actualizado.subscribe(aviso);boton('Descartar');const r=http.expectOne(`${RUTA}/hilo-1/confirmar`);expect(r.request.body.aceptar).toBe(false);r.flush(respuesta());expect(aviso).not.toHaveBeenCalled();});
  it('conserva la clave al reintentar un fallo de conexión',()=>{iniciar();boton('Mis citas');const r=http.expectOne(`${RUTA}/hilo-1/mensajes`);const clave=r.request.headers.get('Idempotency-Key');r.flush({detalle:'Sin conexión'},{status:503,statusText:'Unavailable'});f.detectChanges();boton('Reintentar gestión');const retry=http.expectOne(`${RUTA}/hilo-1/mensajes`);expect(retry.request.headers.get('Idempotency-Key')).toBe(clave);expect(retry.request.body).toEqual({texto:'Mis citas'});retry.flush(respuesta());});
  it('las opciones respetan los permisos de recepción',()=>{iniciarSesionCon(['paciente.leer_administrativo','agenda.leer']);iniciar();expect(f.nativeElement.textContent).not.toContain('Resumen clínico');expect(f.nativeElement.textContent).not.toContain('Mis pagos');expect(f.nativeElement.textContent).not.toContain('Motivo para cancelar');});
  it('muestra elementos clínicos locales y pagos sin imprimir JSON',()=>{iniciar();decir('Resumen clínico',respuesta({datos:{elementos:[{titulo:'Alergias',detalle:'Sin alergias registradas'}],pagos:[{importe:'45.00',moneda:'USD',estado:'Pendiente',cita:'2026-04-16T15:00:00Z'}]}}));expect(f.nativeElement.textContent).toContain('Sin alergias registradas');expect(f.nativeElement.textContent).toContain('45.00 USD');});
  it('aparta solamente el número de un horario ofrecido',()=>{iniciar();decir('Buscar horarios',respuesta({datos:{turnos:[{inicio:'2026-04-16T15:00:00Z',fin:'2026-04-16T15:30:00Z'}],zona_horaria:'America/Guayaquil'}}));boton('Apartar horario');const r=http.expectOne(`${RUTA}/hilo-1/mensajes`);expect(r.request.body.texto).toBe('1');r.flush(respuesta({propuesta:{...propuesta,nombre:'hold_slot',titulo:'Apartar horario',argumentos:{inicio:'2026-04-16T15:00:00Z'}}}));});
  it('emite cierre y permite reintentar la apertura fallida',()=>{f.detectChanges();http.expectOne(RUTA).flush({},{status:503,statusText:'Unavailable'});f.detectChanges();boton('Reintentar conexión');http.expectOne(RUTA).flush(respuesta());f.detectChanges();const cerrar=vi.fn();f.componentInstance.cerrar.subscribe(cerrar);boton('Cerrar');expect(cerrar).toHaveBeenCalledOnce();});
});
