"""registros_paciente_y_documentos

Revision ID: 20261007_031
Revises: 20261007_030
Fecha: 2026-10-07 21:28:59.401519+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20261007_031"
down_revision: str | None = "20261007_030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registro_paciente",
        sa.Column("clinica_id", sa.Uuid(), nullable=False),
        sa.Column("paciente_id", sa.Uuid(), nullable=False),
        sa.Column("profesional_id", sa.Uuid(), nullable=False),
        sa.Column("cita_id", sa.Uuid(), nullable=True),
        sa.Column("especialidad_id", sa.Uuid(), nullable=False),
        sa.Column("sede_id", sa.Uuid(), nullable=True),
        sa.Column("raiz_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("vigente", sa.Boolean(), nullable=False),
        sa.Column("tipo", sa.String(length=16), nullable=False),
        sa.Column("titulo", sa.String(length=200), nullable=False),
        sa.Column("contenido", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nivel_sensibilidad", sa.String(length=2), nullable=False),
        sa.Column("motivo", sa.Text(), nullable=False),
        sa.Column("anulado", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("creado_por", sa.Uuid(), nullable=True),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actualizado_por", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "nivel_sensibilidad IN ('N2', 'N3')",
            name=op.f("ck_registro_paciente_sensibilidad_valida"),
        ),
        sa.CheckConstraint(
            "tipo IN ('FACIOGRAMA', 'PRESUPUESTO', 'COTIZACION', 'RECETA')",
            name=op.f("ck_registro_paciente_tipo_valido"),
        ),
        sa.CheckConstraint(
            "length(motivo) >= 5", name=op.f("ck_registro_paciente_motivo_obligatorio")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_registro_paciente_version_positiva")),
        sa.ForeignKeyConstraint(
            ["cita_id"],
            ["cita.id"],
            name=op.f("fk_registro_paciente_cita_id_cita"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinica.id"],
            name=op.f("fk_registro_paciente_clinica_id_clinica"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["especialidad_id"],
            ["especialidad.id"],
            name=op.f("fk_registro_paciente_especialidad_id_especialidad"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["paciente.id"],
            name=op.f("fk_registro_paciente_paciente_id_paciente"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profesional_id"],
            ["profesional.id"],
            name=op.f("fk_registro_paciente_profesional_id_profesional"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sede_id"],
            ["sede.id"],
            name=op.f("fk_registro_paciente_sede_id_sede"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registro_paciente")),
        sa.UniqueConstraint("raiz_id", "version", name=op.f("uq_registro_paciente_raiz_id")),
    )
    op.create_index(
        "ix_registro_paciente_contexto",
        "registro_paciente",
        ["clinica_id", "paciente_id", "especialidad_id"],
        unique=False,
    )
    op.create_index(
        "uq_registro_paciente_vigente",
        "registro_paciente",
        ["raiz_id"],
        unique=True,
        postgresql_where=sa.text("vigente"),
    )
    op.create_table(
        "entrega_documento",
        sa.Column("registro_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expira_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("intentos_fallidos", sa.Integer(), nullable=False),
        sa.Column("anulada", sa.Boolean(), nullable=False),
        sa.Column("outbox_id", sa.Uuid(), nullable=True),
        sa.Column("clave_idempotencia", sa.String(length=64), nullable=False),
        sa.Column("token_cifrado", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("creado_por", sa.Uuid(), nullable=True),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actualizado_por", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "intentos_fallidos >= 0", name=op.f("ck_entrega_documento_intentos_no_negativos")
        ),
        sa.ForeignKeyConstraint(
            ["outbox_id"],
            ["outbox_mensaje.id"],
            name=op.f("fk_entrega_documento_outbox_id_outbox_mensaje"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["registro_id"],
            ["registro_paciente.id"],
            name=op.f("fk_entrega_documento_registro_id_registro_paciente"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entrega_documento")),
        sa.UniqueConstraint(
            "clave_idempotencia", name=op.f("uq_entrega_documento_clave_idempotencia")
        ),
        sa.UniqueConstraint("token_hash", name=op.f("uq_entrega_documento_token_hash")),
    )
    op.drop_constraint(op.f("ck_consentimiento_tipo_valido"), "consentimiento", type_="check")
    op.create_check_constraint(
        "tipo_valido",
        "consentimiento",
        "tipo IN ('TRATAMIENTO_DATOS', 'COMUNICACION_WHATSAPP', 'RECORDATORIOS_MEDICACION', "
        "'COMPARTIR_CON_TERCEROS', 'PROMOCIONES', 'DOCUMENTOS_WHATSAPP')",
    )
    op.execute("""
        CREATE FUNCTION registro_paciente_inmutable() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'El registro no se elimina: cree una versión de anulación.' USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'UPDATE' THEN
                IF NOT (OLD.vigente AND NOT NEW.vigente) OR
                   (to_jsonb(OLD) - 'vigente' - 'actualizado_en') IS DISTINCT FROM
                   (to_jsonb(NEW) - 'vigente' - 'actualizado_en') THEN
                    RAISE EXCEPTION 'El contenido del registro es inmutable.' USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END IF;
            IF NEW.version = 1 AND NEW.raiz_id <> NEW.id THEN
                RAISE EXCEPTION 'La primera versión debe ser la raíz.' USING ERRCODE = '23514';
            END IF;
            IF NEW.version > 1 AND NOT EXISTS (
                SELECT 1 FROM registro_paciente r WHERE r.raiz_id = NEW.raiz_id AND r.version = NEW.version - 1
                AND r.clinica_id = NEW.clinica_id AND r.paciente_id = NEW.paciente_id
                AND r.profesional_id = NEW.profesional_id AND r.especialidad_id = NEW.especialidad_id
                AND r.tipo = NEW.tipo AND NOT r.vigente AND NOT r.anulado
                AND (r.nivel_sensibilidad <> 'N3' OR NEW.nivel_sensibilidad = 'N3')
            ) THEN
                RAISE EXCEPTION 'La versión no continúa un registro válido.' USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER registro_paciente_inmutable BEFORE INSERT OR UPDATE OR DELETE ON registro_paciente
            FOR EACH ROW EXECUTE FUNCTION registro_paciente_inmutable();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER registro_paciente_inmutable ON registro_paciente")
    op.execute("DROP FUNCTION registro_paciente_inmutable()")
    op.drop_constraint(op.f("ck_consentimiento_tipo_valido"), "consentimiento", type_="check")
    op.create_check_constraint(
        "tipo_valido",
        "consentimiento",
        "tipo IN ('TRATAMIENTO_DATOS', 'COMUNICACION_WHATSAPP', 'RECORDATORIOS_MEDICACION', "
        "'COMPARTIR_CON_TERCEROS', 'PROMOCIONES')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entrega_documento")
    op.drop_index(
        "uq_registro_paciente_vigente",
        table_name="registro_paciente",
        postgresql_where=sa.text("vigente"),
    )
    op.drop_index("ix_registro_paciente_contexto", table_name="registro_paciente")
    op.drop_table("registro_paciente")
    # ### end Alembic commands ###
