"""indicaciones postconsulta

Revision ID: 20261006_006
Revises: 20261006_005
Fecha: 2026-10-05 23:11:37.403532+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20261006_006"
down_revision: str | None = "20261006_005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indicacion_postconsulta",
        sa.Column("clinica_id", sa.Uuid(), nullable=False),
        sa.Column("paciente_id", sa.Uuid(), nullable=False),
        sa.Column("profesional_id", sa.Uuid(), nullable=False),
        sa.Column("cita_id", sa.Uuid(), nullable=True),
        sa.Column("receta_id", sa.Uuid(), nullable=True),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expira_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("intentos_fallidos", sa.SmallInteger(), nullable=False),
        sa.Column("bloqueada", sa.Boolean(), nullable=False),
        sa.Column("lecturas", sa.SmallInteger(), nullable=False),
        sa.Column("primera_lectura_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultima_lectura_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anulada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_anulacion", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("creado_por", sa.Uuid(), nullable=True),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actualizado_por", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "anulada_en IS NULL OR motivo_anulacion IS NOT NULL",
            name=op.f("ck_indicacion_postconsulta_anulacion_con_motivo"),
        ),
        sa.CheckConstraint(
            "length(texto) BETWEEN 10 AND 4000",
            name=op.f("ck_indicacion_postconsulta_texto_acotado"),
        ),
        sa.ForeignKeyConstraint(
            ["cita_id"],
            ["cita.id"],
            name=op.f("fk_indicacion_postconsulta_cita_id_cita"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinica.id"],
            name=op.f("fk_indicacion_postconsulta_clinica_id_clinica"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["paciente.id"],
            name=op.f("fk_indicacion_postconsulta_paciente_id_paciente"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profesional_id"],
            ["profesional.id"],
            name=op.f("fk_indicacion_postconsulta_profesional_id_profesional"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["receta_id"],
            ["receta.id"],
            name=op.f("fk_indicacion_postconsulta_receta_id_receta"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicacion_postconsulta")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_indicacion_postconsulta_token_hash")),
    )
    op.create_index(
        "ix_indicacion_postconsulta_paciente",
        "indicacion_postconsulta",
        ["paciente_id", "creado_en"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_indicacion_postconsulta_paciente", table_name="indicacion_postconsulta")
    op.drop_table("indicacion_postconsulta")
    # ### end Alembic commands ###
