"""lista de espera y oferta de turnos

Revision ID: ca0c0c08ad86
Revises: 57eead6d29aa
Fecha: 2026-09-12 01:59:14.368232+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ca0c0c08ad86"
down_revision: str | None = "57eead6d29aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lista_espera",
        sa.Column("clinica_id", sa.Uuid(), nullable=False),
        sa.Column("paciente_id", sa.Uuid(), nullable=False),
        sa.Column("sede_id", sa.Uuid(), nullable=False),
        sa.Column("especialidad_id", sa.Uuid(), nullable=False),
        sa.Column("servicio_id", sa.Uuid(), nullable=True),
        sa.Column("profesional_id", sa.Uuid(), nullable=True),
        sa.Column("estado", sa.String(length=16), nullable=False),
        sa.Column("prioridad", sa.String(length=8), nullable=False),
        sa.Column("preferencias", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("horas_antelacion_minima", sa.SmallInteger(), nullable=False),
        sa.Column("disponible_desde", sa.Date(), nullable=True),
        sa.Column("disponible_hasta", sa.Date(), nullable=True),
        sa.Column("ofertas_realizadas", sa.SmallInteger(), nullable=False),
        sa.Column("ofertas_vencidas", sa.SmallInteger(), nullable=False),
        sa.Column("nota", sa.Text(), nullable=True),
        sa.Column("cita_resultante_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("creado_por", sa.Uuid(), nullable=True),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actualizado_por", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "estado IN ('ACTIVA', 'OFERTADA', 'CUMPLIDA', 'CANCELADA', 'EXPIRADA')",
            name=op.f("ck_lista_espera_estado_espera_valido"),
        ),
        sa.CheckConstraint(
            "prioridad IN ('NORMAL', 'ALTA')", name=op.f("ck_lista_espera_prioridad_valida")
        ),
        sa.CheckConstraint(
            "disponible_hasta IS NULL OR disponible_desde IS NULL OR disponible_hasta >= disponible_desde",
            name=op.f("ck_lista_espera_ventana_coherente"),
        ),
        sa.CheckConstraint(
            "horas_antelacion_minima >= 0 AND horas_antelacion_minima <= 168",
            name=op.f("ck_lista_espera_antelacion_razonable"),
        ),
        sa.ForeignKeyConstraint(
            ["cita_resultante_id"],
            ["cita.id"],
            name=op.f("fk_lista_espera_cita_resultante_id_cita"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinica.id"],
            name=op.f("fk_lista_espera_clinica_id_clinica"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["especialidad_id"],
            ["especialidad.id"],
            name=op.f("fk_lista_espera_especialidad_id_especialidad"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["paciente.id"],
            name=op.f("fk_lista_espera_paciente_id_paciente"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profesional_id"],
            ["profesional.id"],
            name=op.f("fk_lista_espera_profesional_id_profesional"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sede_id"], ["sede.id"], name=op.f("fk_lista_espera_sede_id_sede"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["servicio_id"],
            ["servicio.id"],
            name=op.f("fk_lista_espera_servicio_id_servicio"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lista_espera")),
    )
    op.create_index(
        "ix_espera_candidatos",
        "lista_espera",
        ["sede_id", "especialidad_id", "prioridad", "creado_en"],
        unique=False,
        postgresql_where=sa.text("estado = 'ACTIVA'"),
    )
    op.create_index(
        "ix_espera_sin_duplicados",
        "lista_espera",
        ["paciente_id", "sede_id", "especialidad_id"],
        unique=True,
        postgresql_where=sa.text("estado IN ('ACTIVA', 'OFERTADA')"),
    )
    op.create_table(
        "oferta_turno",
        sa.Column("lista_espera_id", sa.Uuid(), nullable=False),
        sa.Column("cita_liberada_id", sa.Uuid(), nullable=False),
        sa.Column("estado", sa.String(length=16), nullable=False),
        sa.Column("expira_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("respondida_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_rechazo", sa.Text(), nullable=True),
        sa.Column("cita_creada_id", sa.Uuid(), nullable=True),
        sa.Column("canal", sa.String(length=16), nullable=False),
        sa.Column("notificada", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("creado_por", sa.Uuid(), nullable=True),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actualizado_por", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "estado <> 'ACEPTADA' OR cita_creada_id IS NOT NULL",
            name=op.f("ck_oferta_turno_aceptada_exige_cita"),
        ),
        sa.CheckConstraint(
            "estado = 'OFRECIDA' OR respondida_en IS NOT NULL OR estado = 'EXPIRADA'",
            name=op.f("ck_oferta_turno_respuesta_exige_instante"),
        ),
        sa.CheckConstraint(
            "estado IN ('OFRECIDA', 'ACEPTADA', 'RECHAZADA', 'EXPIRADA', 'PERDIDA')",
            name=op.f("ck_oferta_turno_estado_oferta_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["cita_creada_id"],
            ["cita.id"],
            name=op.f("fk_oferta_turno_cita_creada_id_cita"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cita_liberada_id"],
            ["cita.id"],
            name=op.f("fk_oferta_turno_cita_liberada_id_cita"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lista_espera_id"],
            ["lista_espera.id"],
            name=op.f("fk_oferta_turno_lista_espera_id_lista_espera"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oferta_turno")),
    )
    op.create_index(
        "ix_oferta_activa_por_entrada",
        "oferta_turno",
        ["lista_espera_id"],
        unique=True,
        postgresql_where=sa.text("estado = 'OFRECIDA'"),
    )
    op.create_index(
        "ix_oferta_activa_unica",
        "oferta_turno",
        ["cita_liberada_id"],
        unique=True,
        postgresql_where=sa.text("estado = 'OFRECIDA'"),
    )
    op.create_index(
        "ix_oferta_vencidas",
        "oferta_turno",
        ["expira_en"],
        unique=False,
        postgresql_where=sa.text("estado = 'OFRECIDA'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_oferta_vencidas",
        table_name="oferta_turno",
        postgresql_where=sa.text("estado = 'OFRECIDA'"),
    )
    op.drop_index(
        "ix_oferta_activa_unica",
        table_name="oferta_turno",
        postgresql_where=sa.text("estado = 'OFRECIDA'"),
    )
    op.drop_index(
        "ix_oferta_activa_por_entrada",
        table_name="oferta_turno",
        postgresql_where=sa.text("estado = 'OFRECIDA'"),
    )
    op.drop_table("oferta_turno")
    op.drop_index(
        "ix_espera_sin_duplicados",
        table_name="lista_espera",
        postgresql_where=sa.text("estado IN ('ACTIVA', 'OFERTADA')"),
    )
    op.drop_index(
        "ix_espera_candidatos",
        table_name="lista_espera",
        postgresql_where=sa.text("estado = 'ACTIVA'"),
    )
    op.drop_table("lista_espera")
    # ### end Alembic commands ###
