"""pagos administrativos por cita

Revision ID: c544fe09104b
Revises: 36c3ea203e25
Fecha: 2026-09-13 20:46:06.160653+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c544fe09104b"
down_revision: str | None = "36c3ea203e25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pago",
        sa.Column("clinica_id", sa.Uuid(), nullable=False),
        sa.Column("cita_id", sa.Uuid(), nullable=False),
        sa.Column("importe", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("metodo", sa.String(length=20), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("referencia", sa.String(length=100), nullable=True),
        sa.Column("comentario", sa.String(length=500), nullable=True),
        sa.Column("validado_por", sa.Uuid(), nullable=True),
        sa.Column("validado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("creado_por", sa.Uuid(), nullable=True),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actualizado_por", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "estado IN ('PENDING', 'PROOF_RECEIVED', 'UNDER_REVIEW', 'CONFIRMED', 'REJECTED', 'REFUND_PENDING')",
            name=op.f("ck_pago_estado_pago_valido"),
        ),
        sa.CheckConstraint(
            "metodo IN ('EFECTIVO', 'TRANSFERENCIA')", name=op.f("ck_pago_metodo_pago_valido")
        ),
        sa.CheckConstraint("moneda = 'USD'", name=op.f("ck_pago_moneda_usd")),
        sa.CheckConstraint("importe > 0", name=op.f("ck_pago_importe_positivo")),
        sa.ForeignKeyConstraint(["cita_id"], ["cita.id"], name=op.f("fk_pago_cita_id_cita")),
        sa.ForeignKeyConstraint(
            ["clinica_id"], ["clinica.id"], name=op.f("fk_pago_clinica_id_clinica")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pago")),
        sa.UniqueConstraint("cita_id", name="uq_pago_cita"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pago")
    # ### end Alembic commands ###
