"""sesiones de demostracion del agente

Revision ID: c6cb53c8c608
Revises: c544fe09104b
Fecha: 2026-09-14 02:06:14.902285+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c6cb53c8c608"
down_revision: str | None = "c544fe09104b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sesion_agente_demo",
        sa.Column("conversacion_id", sa.Uuid(), nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("clinica_id", sa.Uuid(), nullable=False),
        sa.Column("paciente_id", sa.Uuid(), nullable=False),
        sa.Column("negocio", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("memoria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expira_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["clinica_id"], ["clinica.id"], name=op.f("fk_sesion_agente_demo_clinica_id_clinica")
        ),
        sa.ForeignKeyConstraint(
            ["conversacion_id"],
            ["conversacion.id"],
            name=op.f("fk_sesion_agente_demo_conversacion_id_conversacion"),
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["paciente.id"],
            name=op.f("fk_sesion_agente_demo_paciente_id_paciente"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuario.id"], name=op.f("fk_sesion_agente_demo_usuario_id_usuario")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sesion_agente_demo")),
        sa.UniqueConstraint("conversacion_id", name=op.f("uq_sesion_agente_demo_conversacion_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sesion_agente_demo")
    # ### end Alembic commands ###
