"""Libro de gastos de la clínica, de solo anulación.

Un gasto no se edita ni se borra: se anula con motivo y se registra otro.
El disparador `gasto_solo_anulacion` lo garantiza también frente a SQL
directo: la única actualización admitida pasa de REGISTRADO a ANULADO
rellenando quién, cuándo y por qué, sin tocar ninguna otra columna.

Revision ID: 20261007_029
Revises: 20261006_028
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20261007_029"
down_revision: str | None = "20261006_028"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SQL_FUNCION_SOLO_ANULACION = """
CREATE OR REPLACE FUNCTION gasto_solo_anulacion()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'El libro de gastos no admite borrados: anule el gasto con un motivo.'
            USING ERRCODE = 'insufficient_privilege';
    END IF;
    IF OLD.estado <> 'REGISTRADO' OR NEW.estado <> 'ANULADO'
       OR (NEW.id, NEW.clinica_id, NEW.sede_id, NEW.fecha, NEW.categoria, NEW.descripcion,
           NEW.proveedor, NEW.importe, NEW.moneda, NEW.metodo, NEW.referencia,
           NEW.creado_por, NEW.creado_en)
          IS DISTINCT FROM
          (OLD.id, OLD.clinica_id, OLD.sede_id, OLD.fecha, OLD.categoria, OLD.descripcion,
           OLD.proveedor, OLD.importe, OLD.moneda, OLD.metodo, OLD.referencia,
           OLD.creado_por, OLD.creado_en)
    THEN
        RAISE EXCEPTION
            'Un gasto solo admite su anulacion; para corregirlo, anulelo y registre otro.'
            USING ERRCODE = 'insufficient_privilege';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gasto",
        sa.Column("clinica_id", sa.Uuid(), nullable=False),
        sa.Column("sede_id", sa.Uuid(), nullable=True),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("categoria", sa.String(length=24), nullable=False),
        sa.Column("descripcion", sa.String(length=300), nullable=False),
        sa.Column("proveedor", sa.String(length=200), nullable=True),
        sa.Column("importe", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("metodo", sa.String(length=20), nullable=False),
        sa.Column("referencia", sa.String(length=100), nullable=True),
        sa.Column("estado", sa.String(length=12), nullable=False),
        sa.Column("creado_por", sa.Uuid(), nullable=True),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("anulado_por", sa.Uuid(), nullable=True),
        sa.Column("anulado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_anulacion", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "(estado = 'REGISTRADO' AND anulado_en IS NULL AND anulado_por IS NULL AND motivo_anulacion IS NULL) OR (estado = 'ANULADO' AND anulado_en IS NOT NULL AND anulado_por IS NOT NULL AND length(btrim(motivo_anulacion)) > 0)",
            name=op.f("ck_gasto_anulacion_coherente"),
        ),
        sa.CheckConstraint(
            "categoria IN ('INSUMOS', 'LABORATORIO', 'NOMINA', 'HONORARIOS', 'ARRIENDO', 'SERVICIOS_BASICOS', 'MANTENIMIENTO', 'EQUIPAMIENTO', 'MARKETING', 'IMPUESTOS', 'OTROS')",
            name=op.f("ck_gasto_categoria_valida"),
        ),
        sa.CheckConstraint(
            "estado IN ('REGISTRADO', 'ANULADO')", name=op.f("ck_gasto_estado_valido")
        ),
        sa.CheckConstraint(
            "metodo IN ('EFECTIVO', 'TRANSFERENCIA', 'TARJETA')",
            name=op.f("ck_gasto_metodo_valido"),
        ),
        sa.CheckConstraint("moneda = 'USD'", name=op.f("ck_gasto_moneda_usd")),
        sa.CheckConstraint("importe > 0", name=op.f("ck_gasto_importe_positivo")),
        sa.CheckConstraint(
            "length(btrim(descripcion)) > 0", name=op.f("ck_gasto_descripcion_no_vacia")
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"], ["clinica.id"], name=op.f("fk_gasto_clinica_id_clinica")
        ),
        sa.ForeignKeyConstraint(["sede_id"], ["sede.id"], name=op.f("fk_gasto_sede_id_sede")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gasto")),
    )
    op.create_index("ix_gasto_clinica_fecha", "gasto", ["clinica_id", "fecha"], unique=False)
    op.create_index("ix_gasto_sede_fecha", "gasto", ["sede_id", "fecha"], unique=False)
    # ### end Alembic commands ###
    op.execute(SQL_FUNCION_SOLO_ANULACION)
    op.execute(
        "CREATE TRIGGER gasto_solo_anulacion BEFORE UPDATE OR DELETE ON gasto "
        "FOR EACH ROW EXECUTE FUNCTION gasto_solo_anulacion()"
    )
    op.execute(
        "CREATE TRIGGER gasto_sin_vaciado BEFORE TRUNCATE ON gasto "
        "FOR EACH STATEMENT EXECUTE FUNCTION tabla_solo_insercion()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS gasto_sin_vaciado ON gasto")
    op.execute("DROP TRIGGER IF EXISTS gasto_solo_anulacion ON gasto")
    op.execute("DROP FUNCTION IF EXISTS gasto_solo_anulacion()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_gasto_sede_fecha", table_name="gasto")
    op.drop_index("ix_gasto_clinica_fecha", table_name="gasto")
    op.drop_table("gasto")
    # ### end Alembic commands ###
